// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  productsSidebar: [
    {
      type: 'category',
      label: '상품',
      collapsible: false,
      collapsed: false,
      items: [
        'products/introduction',
      ]
    }
  ],

  lsSidebar: [
    {
      type: 'category',
      label: '라이선스',
      collapsible: false,
      collapsed: false,
      items: [
        'license/license',
      ]
    }
  ],

  releaseSidebar: [
    {
      type: 'category',
      label: 'What\'s New',
      collapsible: false,
      collapsed: false,
      link: {
        type: 'doc',
        id: 'release-notes/new-features',
      },
      items: [
        'release-notes/release-notes'
      ]
    }
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
